tailscale/setec

- client/setec/client.go
> client: implement the base client API

- db/db_test.go
Per https://github.com/golang/go/wiki/CodeReviewComments#useful-test-failures
> db: include got, want output in test failures

- .github/workflows/go-presubmit.yml
- cmd/setec/setec.go
- server/server.go
We will probably want to do something more sophisticated later, but for now
it's nice to run all the tests and satisfy staticcheck.
Also: Fix up a couple things staticcheck noticed.
> .github: add a lightweight CI check

- acl/acl.go
- acl/acl_test.go
- db/db_test.go
> acl: define a Secret type with a Match function

- acl/acl.go
- acl/acl_test.go
- audit/audit.go
- db/db.go
- db/db_test.go
> acl: rename ActionList to ActionInfo

- client/setec/cache.go
- client/setec/client.go
- client/setec/store.go
- client/setec/store_test.go
A Store wraps an API client to give the caller a transparent way to get secret
values that automatically stay up-to-date as values change on the server.
> client: implement the Store type

- client/setec/store.go
- client/setec/store_test.go
- counter_poll_initiated: total update polls initiated
- counter_poll_errors: errors from the server while polling
- counter_secret_fetch: number of secret values fetched
- timestamp_latest_poll: timestamp of the latest poll
> client: add some basic metrics to the Store

- cmd/setec/setec.go
- server/server.go
- counter_api_calls: total calls to each API method
- counter_api_bad_request: invalid requests (by method)
- counter_api_forbidden: forbidden (by method)
- counter_api_internal_error: other errors (by method)
> server: add basic Server metrics

- audit/audit.go
- audit/audit_test.go
> audit: ensure Close closes even if Sync fails

- cmd/setec/setec.go
> cmd/setec: add an info subcommand

- client/setec/store.go
> client/setec: poll hourly by default in Store, not minutely

- server/server.go
- server/static/style.css
- server/templates/index.html
---
Using my usual strategy of stealing bits of CSS from elsewhere (today: tailsql), and then still have it be ugly enough that someone will hate it and send a better PR :joy:
> server: add a very basic, ugly HTML thing for humans to look at

- client/setec/store.go
- client/setec/store_test.go
Some tools have "optional" integrations (e.g., callouts to Slack) that are used
if an API token is available but skipped without error if not, and you can
choose to run with or without it.
To support this, add an AllowLookup option to the Store config. When set, this
permits a Store to start up without a complete list of secrets, and allows the
caller to look up new secrets into the collection on-demand.
Unlike pre-declared secrets, lookups can fail and will not be automatically
retried, but if a lookup succeeds the secret becomes a normal part of the
store's collection.
> client/store: add Lookup methods and AllowLookup option

- client/setec/store.go
If a cache is configured and we have to page in any new secrets during
initialization, flush the cache before starting the polling loop to ensure we
have last-known-good values even if we restart before the next poll.
> client/setec: flush cache after initialization if needed

- cmd/setec/setec.go
- db/db.go
- db/kv.go
- go.mod
- go.sum
- server/backup.go
- server/server.go
- setectest/server.go
> server: implement periodic backup to S3

- cmd/setec/setec.go
- server/backup.go
- server/server.go
> server: pass in a region for S3 backups

- server/server.go
As a temporary measure to allow us to migrate capability names away from the
https:// prefix, if we don't get a result without the prefix, try again with
it.
> server: add a temporary check for capability name migration

- go.mod
- go.sum
- server/server_test.go
- setectest/server.go
Update json.RawMessage to tailcfg.RawMessage in peer caps.
> go.mod: update tailscale.com to commit d9ae7d670e43

- cmd/setec/setec.go
Certain secret types, notably SSH keys, care about the leading and trailing
whitespace we usually trim from plain text secrets by default. Add a flag to
permit this to not happen.
> cmd/setec: add --verbatim flag to the "put" subcommand

- client/setec/client_test.go
- client/setec/store.go
Since the FileClient has no way (by design) to get new secrets if any are
missing at startup, special case that and fail rather than block waiting for
values that can never arrive.
> client/setec: fail quickly when missing secrets with a FileClient

- docs/README.md
- docs/server.md
Add a basic outline of how to run a setec server.
Updates tailscale/tailscale#12010
> docs: add server.md

- cmd/setec/setec.go
- go.mod
- go.sum
MergeFlags(true) is now the default, so we can remove that.
> go.mod: update command to v0.1.15
