tailscale/setec

db/db.go
db/db_test.go

Although we can certainly store an empty secret name, an empty name is likely
either a programming error, or someone trying to be too clever.
We can always relax the constraint later if we want. For now, make the DB
enforce non-empty names when secrets are Put.

db: disallow Put with an empty secret name

---

client/setec/client.go
cmd/setec/setec.go
go.mod
server/server.go
types/api/api.go

---
Dev server is running at https://setec-dev.corp.ts.net , you should be able to access it. I configured ACLs to permit kylie@, fromberger@, maisem@ to do anything. Suggested commands:
```
./setec list https://setec-dev.corp.ts.net
./setec get https://setec-dev.corp.ts.net _internal/acl
./setec get --version=2 https://setec-dev.corp.ts.net test
./setec put https://setec-dev.corp.ts.net some-new-secret
```
The UX of having to provide a full HTTPS URL isn't great, but I was ratholing on how to infer the correct query domain and such so as to not end up needing an HTTPS redirect (which eats the body and thus causes other grief), and decided to defer until later. So, for now, icky UX it is.

cmd/setec: implement a basic CLI to manage secrets

---

client/setec/client.go
server/server.go

---
The `Sec-...` header is a temporary thing, just kicking the can down the road a bit before I have to re-learn the state of the art for defense against browser dark arts.

server: switch API to POST, block browser access

---

acl/acl.go
acl/acl_test.go
go.mod
go.sum
server/server.go

---
The live ACL on setec-dev now grants list, put, set-active to `group:prod`. get and delete are ACLd to just us. I verified that everything still works with that ACL, with group information coming from tailscale.

server: pull group membership from tailscale whois

---

db/db_test.go
db/kv.go

When putting a (new) secret, only assign a new version if the new value is
different from the previous most-recent value.  This check does not extend to
all previous values, only the latest. Add tests for same.

db: re-use the version for re-Put of the latest value

---

db/db_test.go
db/kv.go

An alternative to #19, that avoids aliasing both on input and output.
Convert the map value to a string type that marshals like []byte.

db: store secrets in the map as string instead of []byte

---

server/server.go

The localapi guarantees non-nil elements in the whois response, and has a helper to distinguish tagged vs. untagged nodes.

server: simplify extraction of identity from whois

---

acl/acl.go
acl/acl_test.go
db/db.go
db/db_test.go
db/kv.go
go.mod
go.sum
server/server.go

Removes all internal ACL file support, but keeps the _internal namespace reserved for future use.

server, acl: use peer capabilities provided by tailscale

---

audit/audit.go
audit/audit_test.go
db/db.go
db/db_test.go
server/server.go

Two independently reviewable commits: one creates an audit log package with types + a writer, the other replaces the string "from" identity in the rest of the codebase with an audit.Principal struct.
This PR doesn't cause audit logs to happen yet, it's just teeing things up while we figure out the exact semantics that audit logs should have.

audit: start of audit log package

---

client/setec/store.go
client/setec/store_test.go

Instead of polling all the known secrets during initialization, only query for
those we have not yet got any value for. Add logging about what is still
missing.  Increase the maximum retry interval from 1s to 4s.

client: improve initialization and add tests for it

---

db/db_test.go
server/server.go
setectest/dbtest.go
setectest/server.go

This package contains a plug-compatible wrapper around server.Server and db.DB
for use with the httptest package to serve secrets in unit tests.
Pulls the unexported testDB wrapper out of the db_test package into an exported
type, and updates the existing tests to use the new thing. Add a Server wrapper
to do the same for the HTTP plumbing, and include some affordances for setup.

setectest: add a package to simplify testing

---

db/db.go
db/db_test.go
db/kv.go
server/server.go
types/api/api.go

This adds two new API methods:
- /api/delete: deletes all versions of a named secret
- /api/delete-version: deletes one non-active version of a secret
Components:
- db: add deletion methods to the kv type
- db: add database methods for deletion
Delete: remove all versions of the specified secret.
DeleteVersion: remove one (non-active) version of a single secret.
- db: add deletion tests
- api: add deletion request types
- server: add API handlers for deletion

server,db: add support for deletion of secrets

---

client/setec/store.go

Prometheus is not best pleased with a string.

client/setec: use float64 format for the timestamp metric

---

client/setec/client.go
client/setec/store.go
client/setec/store_test.go
db/db.go
server/server.go
server/server_test.go
types/api/api.go

Extend api.GetRequest to include a digest field for an existing value of the
secret the caller knows about. If this field is set, the server will now check
whether the current active version matches this digest, and if so it will not
report a value back to the caller but will send 304 Not Modified.
The client unpacks this status into a sentinel error so the caller can check
for it without having to know about HTTP.

api,server: add support for conditional "get" requests

---

client/setec/store.go
client/setec/store_test.go

For clients that need to be notified when a new secret value is available, the
Watcher encapsulates a Secret with a level-triggered notification channel.

client: add a Watcher type for secret values

---

cmd/setec/setec.go

With a zero minimum width and no padding, columns can abut directly.
Adjust things to ensure we get at least one space between.

cmd/setec: tweak the default tabwriter settings

---

cmd/setec/setec.go

This is mainly to demonstrate and exercise the conditional get option.

cmd/setec: add an --if-changed flag to the get subcommand

---

acl/acl.go
acl/acl_test.go
client/setec/client.go
client/setec/store_test.go
cmd/setec/setec.go
db/db.go
db/db_test.go
server/server.go
server/server_test.go
setectest/dbtest.go
setectest/server.go
types/api/api.go

- api: rename "set-active" to "activate"
- server: rename /api/set-active to /api/active
- client, db: rename SetActiveVersion to Activate
- update test support and tests
Note this will require adjusting the ACLs when we do an import.

all: rename "set-active" to "activate" throughout

---

client/setec/client.go
cmd/setec/setec.go

Related changes:
- client: add methods to call these APIs
- cmd/setec: make handlers shut down cleanly on signal

cmd/setec: add "delete" and "delete-version" subcommands

---

client/setec/client.go
server/server.go
server/server_test.go
types/api/api.go

(downstream of #53)
A mild improvement to client ergonomics.
Add sentinel errors to the api package for "not found" and "access denied"
errors, so that users of the client can inspect for these error types.
Make the server encode "not found" errors as a 404 status instead of 500.  We
did not do this initially for concern about information leakage, but since we
do not get this error until we are already willing to vend the requested data
back to the caller (i.e., upon a successful authorization check), we are not
divulging anything they could not have already inferred.

all: report sentinel errors for common response categories

---

client/setec/store.go

Similar to StaticSecret, but to read from a file once at startup.

client/setec: add a StaticFile helper

---

client/setec/store.go

Turns out the only place you can use it safely, is a place where you should be using StaticFile and handling the error gracefully.

client/setec: remove MustStaticFile

---

client/setec/store.go
client/setec/store_test.go

Updates tailscale/corp#14172.
https://www.youtube.com/watch?v=0MzfOgNXbHc
- Add a cachedSecret wrapper that bundles a SecretValue and a timestamp.
- Track whether secrets are "declared" or "undeclared".
- Store timestamps as epoch seconds for simpler encoding/decoding.
- Add store options.
- Inject a clock for testing.
- Make locks less locky.
- Add tests.

client/store: eventually expire undeclared secrets from the cache

---

go.mod
go.sum

Fix a bug causing --help to be improperly ignored at the end of a command.

go.mod: update command and flax dependencies

---

client/setec/store.go
client/setec/store_test.go

When I changed the cache format, I intended that the old cache would simply
look invalid and be rejected. Because of the way JSON decoding works, though, a
valid JSON value in the wrong shape could result in a cache with invalid
entries.  Notably: An object with expected secret names but the wrong object
shape.
Fix this by explicitly checking for valid secrets after cache loading.

client/setec: check cache validity after decoding

---

client/setec/store.go
docs/README.md
go.mod

(A proposal for discussion)
Allow the program to explicitly check for new secret values at a specific
moment, e.g. in response to a signal or other operator-controlled input.

client/setec: export a Refresh method on the Store

---

client/setec/store.go

This is not functionally problematic, but it annoyed me: Instead of doing what
the comment said (shifting by ±10%), the store shifting always downward by a
fraction of 5%.

client/setec: fix Store jitter computation

---

cmd/setec/setec.go

I debated whether to make an additional flag to specifically request this
behaviour, but since we already sniff the terminal for output I thought I'd
start with this.
Curiously, I noticed we also trim space off a file input, which is kinda OK if
we know the file is text, but could break binary input. We might want a flag to
override that in one direction or other too.

cmd/setec: do not prompt for secret values when stdin is a pipe

---

cmd/setec/setec.go

When reading secret data from a file, only trim leading and trailing whitespace
if the content is valid UTF-8 text, so that we do not accidentally mangle
binary values with whitespace-looking bytes at the head or tail. For example,
in protocol buffer messages, LF (10) is a common tag byte.

cmd/setec: don't trim whitespace from binary file input

---

client/setec/example_test.go
client/setec/fields.go
client/setec/fields_test.go
client/setec/store.go

Given a pointer to a struct with specially-tagged fields, use reflection to
locate these fields and plumb secrets from a setec.Store into them.

fields: parse tagged fields in struct values and apply secrets to them

---

cmd/setec/setec.go

Ordinarily an empty secret value is an error, since that is usually not
intended.  In some cases it may be needed, however, e.g., if a program runs in
multiple environments and some of its secrets are not relevant to all of them.
With the --empty-ok flag, "put" will now permit an empty secret.

cmd/setec: add a flag to allow "put" of an empty secret value

---

client/setec/client.go

The type is small and has no mutable state, there is no need to pass a pointer.

client/setec: pass Client by value everywhere

---

client/setec/store.go
client/setec/store_test.go

Explicitly note that the Secret retains ownership of the bytes it returns, and
document that read-only sharing of the slice is safe.
In addition, add a GetString method to Secret that sugars copying the bytes
into a new string. The caller could also just do this, but having the method
make the intent perhaps more clear.

client/setec: document ownership of Secret values and add GetString

---

client/setec/fields.go
client/setec/fields_test.go
client/setec/store.go
client/setec/store_test.go

Previously, we reused the lifecycle context for dynamic lookups.  Instead, make
those methods (LookupSecret, LookupWatcher, and Fields.Apply)) take their own
context and update the tests accordingly.
This is a breaking change to the store package interface.

client/setec: plumb contexts to dynamic lookup methods of Store

---

client/setec/client.go

As a convenience, if the caller passes version 0 to GetIfChanged in the client,
treat it as a call to plain Get. Document that this is the case.

client/setec: make GetIfChanged fall back to Get for version 0

---

client/setec/store.go

From a discussion with @bradfitz.  We already have single-flighting in the
store for polls anyway, so this is a straightforward extension.
For callers like scertec, it is very likely that a dynamic lookup may have a
large number of goroutines that all want the same secrets near a (re)start.
Single-flight the lookup so they don't all pound the secrets service and then
race on poking the value into the store.

client/setec: single-flight dynamic lookups

---

acl/acl.go
client/setec/client.go
docs/api.md

docs,client: improve documentation on access permissions

---

client/setec/fields.go
client/setec/fields_test.go

In addition to the existing supported types, allow fields whose pointer
implements the encoding.BinaryUnmarshaler interface to receive secret values
via their UnmarshalBinary method.
This may be used to handle structured binary values, or to perform basic
validation on the secret value (e.g., the implementation can report an error if
the value is invalid, but otherwise copy it).

client/setec: allow struct fields that implement UnmarshalBinary

---

client/setec/store.go
client/setec/store_test.go
go.mod
go.sum

We stumbled on a sharp corner, viz., that if you forget to declare a secret to
the Store, the store will start up just fine, but code that refers to that name
will return a nil Secret and panic later at the point of use.
Since a program that does this is already statically incorrect, generate the
panic (with a more helpful diagnostic) immediately when the secret is accessed
rather than letting it show up as a random nil indirection later.
When lookups are enabled, however, retain the current behaviour of reporting a
nil secret or empty Watcher: By enabling lookups the caller has announced that
it is prepared to deal with dynamic conditions, and can be expected to do the
needful.
Add an IsValid method to a Watcher to make this easier to check.

client/setec: panic for undeclared secrets when lookups are disabled

---

cmd/setec/setec.go
docs/README.md
docs/api.md

- docs: add an API Overview section
- cmd/setec: hint how to activate an added secret value

Clarify the interactions among secret versions

---

client/setec/store.go
client/setec/store_test.go

As a convenience for the caller, rather than having to check both for nil and
for an empty value, make the Get and GetString methods return appropriate empty
values (nil for []byte, "" for string) on a nil/zero receiver.

client: return empty secrets from nil Secret and zero Watcher values

---

docs/README.md

docs: add a warning about caching and updates

---

client/setec/store_test.go
setectest/utils.go

Move the unexported utility type into the shared test package.
Update the tests to use the test package version instead.

setectest: add a Ticker type implementing a fake setec.Ticker

---

server/server.go
server/server_test.go
setectest/server.go

Particularly for tests, it is helpful if the database can be given to the
server at construction time, rather than read in off disk.
Add a new DB field to the server.Config. If this field is populated, it takes
precedence over the DBPath and related fields. Otherwise, the DBPath, Key, and
AuditLog fields are all required (as before) and have the same semantics.

server,setectest: allow creating a server with a pre-made database

---

client/setec/store.go
client/setec/store_test.go

1. Don't allow an empty secret name to be declared.  While in principle this
could be fine, it is weird and not worth supporting.
2. Deduplicate secret names before initialization. I originally thought this
was not needed, but because of the way we merge cached results with the
initialization step, duplicates can "poison" the initialization state.

client: fix corner cases in secret declaration

---

client/setec/fields.go

I neglected to do this in #118.

client: remove support for the now-unexported watcher from Fields

---

client/setec/fields.go
client/setec/fields_test.go

This error allows the caller to check whether a candidate struct has any
setec-tagged fields to decide whether to include it in a store config.

client: add a sentinel error for ParseFields

---

db/db.go
db/kv.go

Since we wrote this code, the maps and slices packages have been promoted to
mainline and expanded, so we no longer need to depend on x/exp for them.

all: replace exp/maps and exp/slices with base packages

---

client/setec/fields.go
go.mod

Since we wrote this code, the maps and slices packages have been promoted to mainline and expanded, so we no longer need to depend on x/exp for them.
Follow up to #128

client/setec: update slices to mainline from x/exp

---

docs/README.md

Updates tailscale/tailscale#15207
- Separates the two sub pages from the readme TOC
- Adds a Getting Started section to make it harder to miss the setup doc
- Adds a more obvious link to the API docs page in the API overview section
- Adds instructions for where to file issues

docs: Improve documentation UX

---

client/setec/client.go

Steer readers toward using a Store for read access to secrets at runtime, and
reinforce the convention of loading secrets or failing at startup to mitigate
concerns about reachability. Add links to the background and API docs.
It's not straightforward to make a standard Example, since the fixtures need a
testing.T that is not available. But at least this should address part of the
concern you raised about visibility. There is an existing example test, but it
is not surfaced in the pkgsite output. Maybe we can link to it directly, or
maybe pull out some fake test plumbing? That's a larger matter and this should
at least improve matters meanwhile.

client/setec: expand package docs with more usage guidance
